[package]
name = "e-learning_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-cors = "0.7.1"
actix-multipart = "0.7.2"
actix-web = "4.10.2"
argon2 = "0.5.3"
diesel = "2.2.8"
dotenvy = "0.15.7"
rand_core = { version = "0.9.3", features = ["std"] }
